### PR TITLE
add supported node versions

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
shurg, anyone have any ideas what's going on here?

**Comment by friday** [comment]
Travis rejected your PR since it breaks support for Node 4 and 6, which doesn't support [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax).

You should test the branch locally in all supported node versions if you try and do something like autofix imo. Or better yet: don't run autofix at all unless you're in agreeance with the maintainer that this is desirable.

**Comment by graingert** [comment]
@friday I am a maintainer

**Comment by graingert** [comment]
@friday also the failure seems to be coming from babel, not node itself.

**Comment by friday** [comment]
Oh, sorry! I couldn't see you listed as a contributor. A maintainer doing maintenance work is something I can't disagree with.

It seems AVA is transpiling the tests. I didn't know this. I tried your branch with ava downgraded to 0.17, and it works. Removing the spread syntax should be fairly simple too, but uglier.

**Comment by friday** [comment]
(I pushed this small change to #65, so you can see it's working)

**Comment by graingert** [comment]
Hmm. Sucks that it's either xo or ava

**Comment by friday** [comment]
Not sure what you're referring to. I think these issues are mostly trivial, and I don't see a big problem with using an older version until it is fixed.

And at least now there is one green pull request, which is progress :)

**Comment by graingert** [comment]
@friday thanks!

**Pull request merged**
