### PR TITLE
[test] Adding a test case for failing method name import

### PR DESCRIPTION
**Pull request by rma4ok**
This new test case will fail if `const imports = {};` is used and passes with `const imports = Object.create(null);`
in https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/rules/core/enhance.js

### CODE REVIEW

**Comment by rma4ok** [comment]
Closes #51 #60 #61 #53 #67 #75

**Comment by rma4ok** [comment]
@richardpringle @iofjuupasli @zarsky-broad @robertherber 
Please upvote 😄

**Comment by mapreal19** [comment]
@rma4ok I guess this is not being maintained anymore?

**Comment by graingert** [comment]
looks like travis CI has broken, I'll need someone to configure github actions and get a passing build running this test

**Comment by mapreal19** [comment]
@graingert I could do that, we should use GitHub actions now

**Comment by graingert** [comment]
@rma4ok can you merge master please?

**Comment by graingert** [comment]
@mapreal19 want to make a new PR for this?

**Comment by rma4ok** [comment]
@graingert I've changed the base branch to `master` and it can be merged in without conflicts

**Comment by graingert** [comment]
@rma4ok it seems CI isn't running here, can you try merging from master?

**Comment by rma4ok** [comment]
@graingert @mapreal19 this PR is closed in favor of a new one based on `master` #98

**Pull request closed without merging**
