### PR TITLE
Added lodash-fp to recommended preset

### PR DESCRIPTION
**Pull request by iddan**
So users won't need to add it by themselves

### CODE REVIEW

**Comment by iddan** [comment]
Can someone review please?

**Comment by iddan** [comment]
?

**Comment by graingert** [comment]
I've recently merged https://github.com/jfmengels/eslint-plugin-lodash-fp/pull/62 which fixed the travis tests. Please could you rebase this PR to re-run the travis tests.

**Comment by iddan** [comment]
recreated at #66

**Pull request closed without merging**
