### PR TITLE
ignore Object.prototype methods when checking for Lodash imports

### LINKED ISSUE #51: TypeError: info.name.replace is not a function, when using eslint-watch
I get the following error when using eslint-watch, and I can't figure out why and how to solve it.

```
TypeError: info.name.replace is not a function
    at buildInfo (C:\Projects\careconsultation\CareConsultationServer\CareConsultation.WebApp\node_modules\eslint-plugin-lodash-fp\rules\core\lodash-util.js:17:28)
```

### PR DESCRIPTION
**Pull request by iofjuupasli**
Fixes #51 

Same issue as in https://github.com/wix/eslint-plugin-lodash/issues/115

### CODE REVIEW

**Comment by iofjuupasli** [comment]
@jfmengels Build fail same as in master. Can you merge, please?

**Comment by richardpringle** [comment]
This actually fixes #60 as well. If this lands, #61 can be closed

**Comment by richardpringle** [comment]
@jfmengels, strongly suggest that you add some contributors who can afford the time to maintain this repo if you don't have the time.

**Comment by graingert** [comment]
I've recently merged https://github.com/jfmengels/eslint-plugin-lodash-fp/pull/62 which fixed the travis tests. Please could you rebase this PR to re-run the travis tests.

**Comment by graingert** [comment]
@iofjuupasli  can you write a test for this?

**Comment by iofjuupasli** [comment]
@graingert rebased
no can't write test - don't know codebase, and have no time, sorry
just copied solution from eslint-plugin-lodash
with fix it works in my project

**Comment by robertherber** [comment]
Any updates on this? Seems like the tests are passing? Why no merge? :)

**Comment by graingert** [comment]
@robertherber I'm waiting for someone to add a test that would fail without this patch

**Comment by rma4ok** [comment]
@graingert here you go https://github.com/jfmengels/eslint-plugin-lodash-fp/pull/89
I've added the test case that is failing without 
```
const imports = Object.create(null);
```

**Pull request closed without merging**
